const BOXES=[[-24,3,0,2,6,52,'wall'],[24,3,0,2,6,52,'wall'],[0,3,-26,50,6,2,'wall'],[0,3,26,50,6,2,'wall'],[-10,1.6,-9,6,3.2,12,'blue'],[10,1.6,9,6,3.2,12,'red'],[9,1.6,-13,11,3.2,5,'olive'],[-9,1.6,13,11,3.2,5,'olive'],[0,1.2,0,4,2.4,5,'crate'],[-18,1,3,3,2,3,'crate'],[18,1,-3,3,2,3,'crate'],[2,1,-19,3,2,3,'crate'],[-2,1,19,3,2,3,'crate']];
const SPAWNS=[[-19,21],[19,-21],[19,21],[-19,-21],[0,22],[0,-22],[-20,0],[20,0]];
const clamp=(n,a,b)=>Math.max(a,Math.min(b,n));
function blocked(x,z){return Math.abs(x)>22.5||Math.abs(z)>24.5||BOXES.some(b=>Math.abs(x-b[0])<b[3]/2+.35&&Math.abs(z-b[2])<b[5]/2+.35)}
function rayBox(o,d,min,max){let lo=0,hi=100;for(let i=0;i<3;i++){if(Math.abs(d[i])<1e-8){if(o[i]<min[i]||o[i]>max[i])return Infinity;}else{let a=(min[i]-o[i])/d[i],b=(max[i]-o[i])/d[i];lo=Math.max(lo,Math.min(a,b));hi=Math.min(hi,Math.max(a,b));if(hi<lo)return Infinity}}return lo}
function wallDistance(o,d){return Math.min(...BOXES.map(b=>rayBox(o,d,[b[0]-b[3]/2,b[1]-b[4]/2,b[2]-b[5]/2],[b[0]+b[3]/2,b[1]+b[4]/2,b[2]+b[5]/2])))}
class Arena{
 constructor(mode='tdm',bots=0){this.mode=mode;this.players={};this.time=300;this.scores=[0,0];this.events=[];this.over=false;this.restart=0;for(let i=0;i<bots;i++)this.add('bot'+i,['GHOST','VIPER','NOVA','REAPER','ECHO','FALCON'][i],true)}
 add(id,name,bot=false){let p={id,name:String(name||'ROOKIE').slice(0,16),bot,team:Object.values(this.players).filter(p=>p.team===0).length<=Object.values(this.players).filter(p=>p.team===1).length?0:1,x:0,z:0,y:1.65,vy:0,yaw:0,pitch:0,hp:100,ammo:30,kills:0,deaths:0,cool:0,reload:0,respawn:0,shield:2,input:{}};this.players[id]=p;this.spawn(p);return p}
 spawn(p){let spots=this.mode==='tdm'?SPAWNS.filter((_,i)=>i%2===p.team):SPAWNS;let s=spots[Math.floor(Math.random()*spots.length)];Object.assign(p,{x:s[0],z:s[1],yaw:Math.atan2(s[0],s[1]),y:1.65,vy:0,hp:100,ammo:30,respawn:0,reload:0,shield:2});}
 input(id,i){let p=this.players[id];if(!p||!i)return;p.input={f:clamp(Number(i.f)||0,-1,1),s:clamp(Number(i.s)||0,-1,1),yaw:Number.isFinite(i.yaw)?i.yaw:0,pitch:clamp(Number(i.pitch)||0,-1.45,1.45),fire:!!i.fire,reload:!!i.reload,jump:!!i.jump,sprint:!!i.sprint,aim:!!i.aim}}
 step(dt){this.events=[];if(this.over){this.restart-=dt;if(this.restart<=0){this.over=false;this.time=300;this.scores=[0,0];for(let p of Object.values(this.players)){p.kills=0;p.deaths=0;this.spawn(p)}}return}this.time-=dt;let all=Object.values(this.players);for(let p of all){p.cool=Math.max(0,p.cool-dt);p.shield=Math.max(0,p.shield-dt);if(p.hp<=0){p.respawn-=dt;if(p.respawn<=0)this.spawn(p);continue}if(p.reload>0){p.reload-=dt;if(p.reload<=0)p.ammo=30}if(p.bot){let t=all.filter(q=>q.id!==p.id&&q.hp>0&&(this.mode==='ffa'||q.team!==p.team)).sort((a,b)=>Math.hypot(a.x-p.x,a.z-p.z)-Math.hypot(b.x-p.x,b.z-p.z))[0];if(t){let a=Math.atan2(-(t.x-p.x),-(t.z-p.z));let dist=Math.hypot(t.x-p.x,t.z-p.z);let phase=Math.sin(this.time*.7+Number(p.id.slice(3))*2);p.input={yaw:a+Math.sin(this.time*3)*.035,pitch:0,f:dist>11?1:0,s:phase>.4?.8:phase<-.4?-.8:0,fire:dist<35&&p.shield===0,reload:p.ammo===0};if(blocked(p.x-Math.sin(a)*.7,p.z-Math.cos(a)*.7)){p.input.yaw=a+1.2;p.input.f=1;p.input.s=1}}}let i=p.input;p.yaw=i.yaw||0;p.pitch=i.pitch||0;let f=i.f||0,s=i.s||0,n=Math.max(1,Math.hypot(f,s)),speed=i.sprint?7:4.6;let dx=(-Math.sin(p.yaw)*f+Math.cos(p.yaw)*s)/n*speed*dt,dz=(-Math.cos(p.yaw)*f-Math.sin(p.yaw)*s)/n*speed*dt;if(!blocked(p.x+dx,p.z))p.x+=dx;if(!blocked(p.x,p.z+dz))p.z+=dz;if(i.jump&&p.y<=1.65)p.vy=5;p.vy-=15*dt;p.y=Math.max(1.65,p.y+p.vy*dt);if(p.y===1.65)p.vy=0;if(i.reload&&p.ammo<30&&p.reload<=0)p.reload=1.8;if(i.fire&&!i.sprint&&p.cool===0&&p.reload<=0&&p.ammo>0){p.shield=0;p.ammo--;p.cool=p.bot?.24:.105;let cp=Math.cos(p.pitch),d=[-Math.sin(p.yaw)*cp,Math.sin(p.pitch),-Math.cos(p.yaw)*cp],o=[p.x,p.y,p.z];let nearest=wallDistance(o,d),hit=null;for(let q of all){if(q.id===p.id||q.hp<=0||q.shield>0||(this.mode==='tdm'&&q.team===p.team))continue;let v=rayBox(o,d,[q.x-.34,q.y-1.65,q.z-.34],[q.x+.34,q.y+.2,q.z+.34]);if(v<nearest){nearest=v;hit=q}}let e={type:'shot',id:p.id,o,d,distance:Math.min(nearest,60),hit:hit?.id};this.events.push(e);if(hit){let head=o[1]+d[1]*nearest>hit.y-.24;hit.hp=Math.max(0,hit.hp-(head?70:28));if(!hit.hp){p.kills++;hit.deaths++;hit.respawn=3;this.scores[p.team]++;this.events.push({type:'kill',name:p.name,victim:hit.name,head,team:p.team})}}}}
 if(this.time<=0||(this.mode==='tdm'?Math.max(...this.scores)>=50:all.some(p=>p.kills>=25))){this.over=true;this.restart=8}}
 snapshot(){return {mode:this.mode,time:this.time,scores:this.scores,over:this.over,restart:this.restart,events:this.events,players:Object.values(this.players).map(({input,...p})=>p)}}
}

module.exports={Arena,BOXES,SPAWNS,blocked,rayBox,wallDistance};
